# fly.toml file generated for fly-rails-playground on 2022-08-11T11:52:31+02:00

app = "fly-rails-playground"

[build]
  [build.args]
    BUNDLER_VERSION = "2.3.7"
    NODE_VERSION = "14"
    RUBY_VERSION = "3.1.2"

[http_service]
  internal_port = 8080
  force_https = true

[env]
  PORT = "8080"
  SERVER_COMMAND = "bundle exec puma -C config/puma.rb"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[deploy]
  release_command = "bundle exec rails db:migrate"
