# fly.toml file generated for fly-rails-playground on 2022-08-11T11:52:31+02:00

app = "fly-rails-playground"
primary_region = "ord"

[build]
  [build.args]
    BUNDLER_VERSION = "2.3.7"
    NODE_VERSION = "14"
    RUBY_VERSION = "3.1.2"
    SERVER_COMMAND = "/app/bin/litefs"

[http_service]
  internal_port = 8080
  force_https = true

[env]
  SERVER_COMMAND = "bundle exec puma -C config/puma.rb"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[deploy]
#  Enable the release command once write forwarding drops in Litefs: https://github.com/superfly/litefs/issues/56
#  release_command = "bundle exec rails db:migrate"
